apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: traceId
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: true
    jsonData:
      httpMethod: GET
      search:
        hide: false
      serviceMap:
        datasourceUid: prometheus
      tracesToMetrics:
        datasourceUid: prometheus
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        tags: [{ key: 'service.name', value: 'application' }]
        queries:
          - name: 'Requests per second'
            query: 'sum(rate(http_server_requests_seconds_count{application="$${__tags}"}[1m]))'
