apiVersion: v1
kind: Namespace
metadata:
  name: cambista-system
  labels:
    app.kubernetes.io/name: cambista-online
    app.kubernetes.io/part-of: fintech-cambista
---
apiVersion: v1
kind: Secret
metadata:
  name: cambista-secrets
  namespace: cambista-system
type: Opaque
stringData:
  POSTGRES_USER:  postgres
  POSTGRES_PASSWORD: postgrespassword
  JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  OAUTH_GOOGLE_CLIENT_ID: google-client-id-placeholder
  OAUTH_GOOGLE_CLIENT_SECRET: google-client-secret-placeholder
  OAUTH_GITHUB_CLIENT_ID: github-client-id-placeholder
  OAUTH_GITHUB_CLIENT_SECRET: github-client-secret-placeholder
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cambista-config
  namespace: cambista-system
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka-service:9092
  REDIS_HOST: redis-service
  REDIS_PORT: 6379
  JWT_EXPIRATION_MS: 3600000
  AUTH_DB_URL: jdbc:postgresql://postgres-auth-service:5432/cambista_auth_db
  RATE_DB_URL: jdbc:postgresql://postgres-rate-service:5432/cambista_rate_db
  WALLET_DB_URL: jdbc:postgresql://postgres-wallet-service:5432/cambista_wallet_db
  TRANSACTION_DB_URL: jdbc:postgresql://postgres-transaction-service:5432/cambista_transaction_db
  SERVICES_AUTH_URL: http://auth-service:8081
  SERVICES_EXCHANGE_RATE_URL: http://exchange-rate-service:8082
  SERVICES_WALLET_LEDGER_URL: http://wallet-ledger-service:8083
  SERVICES_TRANSACTION_URL: http://transaction-service:8084