apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cambista-system

resources:
  - 00-namespace-and-secrets.yaml
  - 01-infra-kafka-redis.yaml
  - 02-infra-databases.yaml
  - 03-auth-service.yaml
  - 04-exchange-rate-service.yaml
  - 05-wallet-ledger-service.yaml
  - 06-transaction-service.yaml
  - 07-api-gateway.yaml
  - 08-frontend.yaml